CREATE TABLE IF NOT EXISTS cattle (
  id CHAR(36) NOT NULL PRIMARY KEY,
  tag_number VARCHAR(64) NOT NULL,
  breed VARCHAR(80) NOT NULL DEFAULT 'Gyr',
  sex ENUM('MALE', 'FEMALE') NOT NULL,
  birth_date DATE NULL,
  status ENUM('ACTIVE', 'INACTIVE', 'UNDER_OBSERVATION') NOT NULL,
  last_risk_score DECIMAL(5,2) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY cattle_tag_number_unique (tag_number),
  KEY cattle_status_idx (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
